---
#loqui_app_config.yaml
name: loqui_app_config

general:
# path to the pre-trained model files
  model_path: 'facebook/wav2vec2-large-960h-lv60-self'
  tokenizer_path: 'facebook/wav2vec2-large-960h-lv60-self'
  # target words and phrases to be detected by the system
  target_words:
    - print
    - hello
    - world
    - for
    - in
    - range
    - colon
    - indent
    - variable
    - function
    - return
    - add
    - subtract
    - multiply
    - divide
    - arithmetic
    - operation
    - argument
    - if
    - else
    - comparison
    - operator
    - equal
    - not equal
    - less than
    - greater than
    - boolean
    - true
    - false
    - and
    - or
    - comment
    - hashtag
    - quote
    - parenthesis
    - brackets
    - curly brackets
    - integer
    - float
    - string

# microphone settings
microphone:
  sample_rate: 16000

audio:
  sample_rate: 16000
    padding: longest

output:
  log_level: INFO

# pydub audio settings
pydub_audio:
  channels: 1
  sample_width: 2
  frame_rate: 16000

# logging settings
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file_path: 'speech_to_code.log'
